### ISSUE TITLE
菜单上的文章内展示错误

### ISSUE THREAD

**Issue by feilongproject** [Yue-plus/hexo-theme-arknights#11]
添加到菜单里的页面（比如about、todo，相对链接为/xxx/index.html）等，在浏览其界面时无法显示评论、目录等（即使在文章内加入`commit: true`），希望能修复一下。

**Comment by Yue-plus** [comment]
在 #8 修复之后，配置文件 `_config.yml` 发生了变化：
```yml
# main menu navigation
menu:
  Home: ''
#  About: about/
#  Contact: contact/
  Archives: archives/
```
> 由于蛋疼的字符串拼接问题
> 现在不要在前面加 `/` 号
