### ISSUE TITLE
网站生成后路径问题

### ISSUE THREAD

**Issue by 135shanchun** [Yue-plus/hexo-theme-arknights#121]
在hexo g 生成了public 后，发现我的背景、主题、文章、404等内容全部丢失
问了我的一位朋友后，他告诉我是路径的问题。我不太懂前端，但是我看到他在css js啥的前面将"/"换为了"./"
具体修改可以看一看我的仓库，我设置了public
这个主题真的非常好，我不舍得换主题，所以请作者尽量快的修复这一个比较严重的bug！
这个bug我不知道其他使用者有没有，但是我看issue里面好像没有提出这个问题。

**Comment by Yue-plus** [comment]
你的网站地址是 <https://135shanchun.github.io/vincent/> 对吗？
这应该不是一个 BUG，而是配置文件错误导致的。
初步断定是你 Hexo 目录下的 `_config.yml` 文件中的（大概第 16、17 行）：

```yaml
# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://arknights.theme.hexo.yue.zone     # 此处不要尾随 / 符号
root: /               # 此处默认为 /
```

另外，如果修改过主题目录内的文件，建议尝试（**先备份原主题目录！**）从主题仓库重新 `clone` 一下主题。

----------------------------------------

我需要 Hexo 目录内的以下文件来判断问题所在：

- `_config.arknights.yml`
- `_config.yml`
- `package.json`
- `.\themes\arknights\_config.yml` （如果存在的话）
