### ISSUE TITLE
希望增加社交链接功能

### ISSUE THREAD

**Issue by feilongproject** [Yue-plus/hexo-theme-arknights#13]
（自己写的代码太丑，希望大佬改一下）
我的代码
1. 在`layout.pug`中的
```
#total-categories
  span.total-title Categories:
  span.total-number= site.categories.length
```
后面添加
```
link(rel="stylesheet", href="/css/about_me.css")
#about_me.about_me
  br
  a(href=theme.social.github.url)
    img(src=theme.social.github.img, alt="social-github")
  a(href=theme.social.weibo.url)
    img(src=theme.social.weibo.img, alt="social-weibo")
  a(href=theme.social.wyy.url)
    img(src=theme.social.wyy.img, alt="social-wyy")
  a(href=theme.social.email.url)
    img(src=theme.social.email.img, alt="social-email")
  a(href=theme.social.wechat.url)
    img(src=theme.social.wechat.img, alt="social-wechat")
  a(href=theme.social.zhihu.url)
    img(src=theme.social.zhihu.img, alt="social-zhihu")
  a(href=theme.social.qq.url)
    img(src=theme.social.qq.img, alt="social-qq")
```
2. 在`about_me.css`中（特地建了一个文件，好浪费）
```
.about_me img {
    height: 20px;
    width: 20px
}
```
3. 在主题配置文件中
```
social:
  github: 
    url: https://github.com/feilongproject
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/github.png
  weibo:
    url: https://weibo.com/feilongproject
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/sina.png
  wyy:
    url: https://music.163.com/user?id=1374209960
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wangyiyun.png
  zhihu:
    url: #
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/zhihu.png
  email:
    url: mailto:1728904631@qq.com
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/email.svg
  wechat: 
    url:
    rcode: https://feilongproject.github.io/img/donate/wechat.jpg
    img: https://cdn.jsdelivr.net/gh/honjun/cdn@1.6/img/social/wechat.png
  qq:
    url: https://wpa.qq.com/msgrd?v=3&uin=1728904631&site=qq&menu=yes
    img: https://im.qq.com/favicon.ico
```
图示
![Snipaste_2020-08-21_17-23-26.jpg](https://i.loli.net/2020/08/21/JlUaduhgDwZqQmM.jpg)
注：从明天起就要高一住校了，再也提不了issues了（哭唧唧）
