### ISSUE TITLE
不同终端访问网站，操作出现协同的情况

### ISSUE THREAD

**Issue by Bitter-S** [Yue-plus/hexo-theme-arknights#164]
比如我在电脑端和手机端同时访问网站的话，手机点击切换深浅主题，电脑端也会切换。电脑端同理
如果两端同时访问了同一篇文章，那么一端进行上下滑动的同时另一端也会跟着滑动
请问出现这种状况的原因是什么？有没有解决办法？
我是在云服务器上建站的，运行hexo后使用了nginx进行反向代理，将80端口转到了4000端口来访问的
麻烦大佬

**Comment by Yue-plus** [comment]
不建议将 [`hexo-server`](https://hexo.io/zh-cn/docs/server) 式用于生产环境！

----------

这个问题是 [`hexo-browsersync`](https://github.com/hexojs/hexo-browsersync) 依赖导致的。

----------

执行以下指令：

```sh
hexo generate
```

这会在 `public/` 目录下生成静态文件，可以把 NIGNX 的 Web 目录定到这里。

或者也可以使用 [`hexo-server`](https://hexo.io/zh-cn/docs/server) 静态模式启动：

```sh
hexo server -p 80
```

然后可以通过 <http://hostname:80> 直接访问。（NGINX 不是必须的。）

----------

如果要保持热更新的话，也可以编辑 `package.json` 文件删除该依赖：

```diff
  "dependencies": {
-   "hexo-browsersync": "^0.3.0",
  }
```

然后使用你喜欢的包管理重新安装依赖。

**Comment by Yue-plus** [comment]
公安备案可以写在版权信息里，编辑 Hexo 目录中的 `_config.arknights.yml` 文件：

![image](https://github.com/Yue-plus/hexo-theme-arknights/assets/33195150/9e4776f9-2367-4489-9aaf-8759aa49cf8f)

```yaml
# 侧边栏
aside:
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
    X公网安备:
      1234567 号: https://beian.mps.gov.cn/#/query/webSearch
```

点击会跳转到备案查询页面
