### ISSUE TITLE
[建议]关于增加音乐播放器的相关建议

### ISSUE THREAD

**Issue by kola63502** [Yue-plus/hexo-theme-arknights#183]
首先！请允许我夸夸这个主题！真的很**酷**啊！
虽然不是用于明日方舟相关的website，但是真的很酷啊！
很喜欢他的风格！

这里是个人关于这个主题的一个_微不足道_的建议！希望有所启发和帮助！
希望能增加音乐播放器的相关功能，如果可以的话，可以实现以下功能：
1. 可以config里自由配置进入网站是否自动播放音乐；
2. 播放音乐后 点击不同的页面 不会使音乐暂停或重新播放；
3. 网页浏览者可自由选择播放、暂停或是静音。

以上是我个人提供的一些想法！

再次感谢能制作出这么**好**的主题！很期待能继续更新！

**Comment by kola63502** [comment]
啊 忘记说了 希望是能配置mp3外链的功能

**Comment by Yue-plus** [comment]
感谢你的喜爱和支持！🎉 你的夸奖让我们备受鼓舞！

现在我在右下角添加了一个可以播放背景音乐的按钮 🎶，你可以拉取最新的更新来体验这个功能！

![Image](https://github.com/user-attachments/assets/551969cc-eeb4-4208-93ca-edc4aa66c3a6)

你可以修改 [`_config.arknights.yml`](https://github.com/Yue-plus/hexo-theme-arknights/blob/main/_config.yml#L93) 文件来进行配置：

```yaml
# 背景音乐
bgm:
  enable: true # 是否启用背景音乐功能
  autoplay: true # 是否自动播放背景音乐
  loop: true # 是否循环播放背景音乐
  src: /audio/bgm.mp3 # 背景音乐链接
```

> [需要用户和网页已有交互行为才会播放背景音乐](https://developer.mozilla.org/zh-CN/docs/Web/Media/Guides/Autoplay#%E8%87%AA%E5%8A%A8%E6%92%AD%E6%94%BE%E7%9A%84%E5%8F%AF%E7%94%A8%E6%80%A7)

抱歉，目前我没有计划加入完整的音乐播放器功能，例如播放列表、歌词显示等。
如果你需要更丰富的音乐播放体验，可以找找其他 Hexo 插件。

> [APlayer](https://github.com/DIYgod/APlayer) 的问题不知道有没有解决 Orz #16 

再次感谢你的支持！如果有更多想法，欢迎继续交流！🚀
