### ISSUE TITLE
评论过后会导致代码高亮出现问题

### ISSUE THREAD

**Issue by Blackfankt** [Yue-plus/hexo-theme-arknights#35]
如图这是没有评论的：
![image](https://user-images.githubusercontent.com/96461491/151523330-e61a5081-b340-4da9-a6ff-2110fec06b32.png)
评论过后：
![image](https://user-images.githubusercontent.com/96461491/151523395-bed6c54c-2a2b-48de-9be7-956a7e7e4777.png)

**Comment by Yue-plus** [comment]
主题已更新，请在主题目录下执行 `git pull` 更新主题。

另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)

**Comment by Blackfankt** [comment]
> 主题已更新，请在主题目录下执行 `git pull` 更新主题。
> 
> 另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)

感谢回复。
更新过后，带有评论的界面代码高亮还是会出现问题，当我删除引入之后发现代码高亮没有了之后将删除操作撤回就没有问题了。。。带有评论的界面也能正常显示。。。

**Comment by Yue-plus** [comment]
> > 主题已更新，请在主题目录下执行 `git pull` 更新主题。
> > 另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)
> 
> 感谢回复。 更新过后，带有评论的界面代码高亮还是会出现问题，当我删除引入之后发现代码高亮没有了之后将删除操作撤回就没有问题了。。。带有评论的界面也能正常显示。。。

点一下评论框再拉上去看也能正常显示？

我看到你 <https://riceater.cn/> 中的打赏按钮还是在的，但评论框没了。

Orz

**Comment by Blackfankt** [comment]
>

> > > 主题已更新，请在主题目录下执行 `git pull` 更新主题。
> > > 另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)
> > 
> > 
> > 感谢回复。 更新过后，带有评论的界面代码高亮还是会出现问题，当我删除引入之后发现代码高亮没有了之后将删除操作撤回就没有问题了。。。带有评论的界面也能正常显示。。。
> 
> 点一下评论框再拉上去看也能正常显示？
> 
> 我看到你 https://riceater.cn/ 中的打赏按钮还是在的，但评论框没了。
> 
> Orz

额，刚刚我正好在调试把评论框关了。。。你说的“点一下评论框再拉上去看也能正常显示？”这个操作是怎么做到的。。。

**Comment by Yue-plus** [comment]
> > 
> 
> > > > 主题已更新，请在主题目录下执行 `git pull` 更新主题。
> > > > 另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)
> > > 
> > > 
> > > 感谢回复。 更新过后，带有评论的界面代码高亮还是会出现问题，当我删除引入之后发现代码高亮没有了之后将删除操作撤回就没有问题了。。。带有评论的界面也能正常显示。。。
> > 
> > 
> > 点一下评论框再拉上去看也能正常显示？
> > 我看到你 https://riceater.cn/ 中的打赏按钮还是在的，但评论框没了。
> > Orz
> 
> 额，刚刚我正好在调试把评论框关了。。。你说的“点一下评论框再拉上去看也能正常显示？”这个操作是怎么做到的。。。

实际上我在查这个bug的时候打开你的网站是正常代码高亮的，然后点到评论框里，再拉上去点下代码框，代码框就会“大惊失色”。

**Comment by Blackfankt** [comment]
> > > 
> > 
> > 
> > > > > 主题已更新，请在主题目录下执行 `git pull` 更新主题。
> > > > > 另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)
> > > > 
> > > > 
> > > > 感谢回复。 更新过后，带有评论的界面代码高亮还是会出现问题，当我删除引入之后发现代码高亮没有了之后将删除操作撤回就没有问题了。。。带有评论的界面也能正常显示。。。
> > > 
> > > 
> > > 点一下评论框再拉上去看也能正常显示？
> > > 我看到你 https://riceater.cn/ 中的打赏按钮还是在的，但评论框没了。
> > > Orz
> > 
> > 
> > 额，刚刚我正好在调试把评论框关了。。。你说的“点一下评论框再拉上去看也能正常显示？”这个操作是怎么做到的。。。
> 
> 实际上我在查这个bug的时候打开你的网站是正常代码高亮的，然后点到评论框里，再拉上去点下代码框，代码框就会“大惊失色”。

嗯对，在更新之前确实有这样的bug，但是现在没有了，可另一个问题是打赏框不见了，我刚刚又关闭评论框在本地调试还是看不见它。。。

**Comment by Yue-plus** [comment]
> > > > 
> > > 
> > > 
> > > > > > 主题已更新，请在主题目录下执行 `git pull` 更新主题。
> > > > > > 另外，检查一下 Hexo 目录下的 `_config.arknights.yml` 文件，是否仍然引入了 `cdn.bootcdn.net` CDN 的 `.js` 与 `.css` 文件，请删除引入。[点击查看示例](https://github.com/Yue-plus/hexo-theme-arknights/commit/dc888b3f0d5e55abcab46a0fa74533c8dfd9e3c3)
> > > > > 
> > > > > 
> > > > > 感谢回复。 更新过后，带有评论的界面代码高亮还是会出现问题，当我删除引入之后发现代码高亮没有了之后将删除操作撤回就没有问题了。。。带有评论的界面也能正常显示。。。
> > > > 
> > > > 
> > > > 点一下评论框再拉上去看也能正常显示？
> > > > 我看到你 https://riceater.cn/ 中的打赏按钮还是在的，但评论框没了。
> > > > Orz
> > > 
> > > 
> > > 额，刚刚我正好在调试把评论框关了。。。你说的“点一下评论框再拉上去看也能正常显示？”这个操作是怎么做到的。。。
> > 
> > 
> > 实际上我在查这个bug的时候打开你的网站是正常代码高亮的，然后点到评论框里，再拉上去点下代码框，代码框就会“大惊失色”。
> 
> 嗯对，在更新之前确实有这样的bug，但是现在没有了，可另一个问题是打赏框不见了，我刚刚又关闭评论框在本地调试还是看不见它。。。

检查一下 Hexo 目录下的 `_config.arknights.yml` 和主题目录下的 `_config.yml` 文件中 `post.reward` 是否都为 `true`：

```yaml
# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  source: false # 是否显示源文件路径
  excerpt: false # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  reward: true # 文章末显示打赏二维码                      《=================== 第23~26行附近
```

可以的话请把这俩文件贴上来。

**Comment by Blackfankt** [comment]
`package.json`:
```
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.1"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-asset-image": "^1.0.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-deployer-git": "^3.0.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^4.1.0",
    "hexo-renderer-pug": "^2.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3"
  }
}

```
主题目录下的`_config.yml`:
```
# html lang
language: zh

# canvas 动态背景
canvas_dust: true

# <body> 背景图片链接
background_image: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # /img/bg.jpg

# 侧边栏
aside:
  in_left: false # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png # 图片链接，建议 1:1 比例
  dr: / # 侧边栏 Dr. 链接
  block_in_top: false # 目前为侧边栏文章目录置顶
  copyright: # 版权声明、备案号等，设置为 null 不显示
    ©: 2020 to 2021
    ICP: ——备案号——

# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: false # 是否显示修改日期
  source: false # 是否显示源文件路径
  excerpt: false # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  reward: true # 文章末显示打赏二维码
# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度
# 归档页；true / false
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# Valine 无后端评论系统
valine:
  enable: true
  app_id: hFMtOfNpU9VjtV3HEvd6CFOr-gzGzoHsz
  app_key: 99rdLFCeg8bKHnu0EwNgbLym

gitalk:
  enable: false
  clientID: # GitHub Application Client ID
  clientSecret: # GitHub Application Client Secret
  repo: # GitHub repository
  owner: # GitHub repository owner
  admin: ["''"] # GitHub repository owner and collaborators (Users who having write access to this repository)
                # Example: ["'adminA'","'adminB'"]
  id: # The unique id of the page
      # Example: location.pathname

# 图表支持
mermaid:
  enable: false
  version: '8.13.5'

# main menu navigation
menu:
  Home: ''
#  About: about/
#  Contact: contact/
  Archives: archives/

# stylesheets loaded in the <head>
stylesheets:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/styles/atom-one-dark-reasonable.min.css

# scripts loaded in the end of the body
scripts:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js

```
emmm我hexo目录下没有设置`_config.arknights.yml`
