### ISSUE TITLE
我的代码块的折叠功能消失了

### ISSUE THREAD

**Issue by misaka-mikoto233** [Yue-plus/hexo-theme-arknights#72]
RT，没有代码块最上面那个显示代码语言、行数和复制按钮的灰框

**Comment by Yue-plus** [comment]
请把 Hexo 目录下的 `_config.arknights.yml`、`_config.yml`、`package.json` 文件贴上来让我康康。

**Comment by misaka-mikoto233** [comment]
### _config.arknights.yml
```yml
# html lang
language: zh

# canvas 动态背景
canvas_dust: true

# <body> 背景图片链接
background_image: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # /img/bg.jpg

# 侧边栏
aside:
  in_left: false # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png # 图片链接，建议 1:1 比例
  dr: / # 侧边栏 Dr. 链接
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  source: false # 是否显示源文件路径
  word_count: true # 是否显示字数统计
  reading_time: false # 是否显示预计阅读时长
  excerpt: false # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  reward: false # 文章末显示打赏二维码
# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度
# 归档页；true / false
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# 搜索框
search:
  enable: false

# Valine 无后端评论系统
valine:
  enable: false
  app_id: # <APP ID>
  app_key: # <APP KEY>
  server_url: # <APP DOMAIN>（LeanCloud 国际版）

gitalk:
  enable: false
  client_id: # GitHub Application Client ID
  client_secret: # GitHub Application Client Secret
  repo: # GitHub repository
  owner: # GitHub repository owner
  admin: [] # GitHub repository owner and collaborators (Users who having write access to this repository)
            # Example: [adminA,adminB]
  id: # (optional) The unique id of the page
      # Example: location.pathname

# 图表支持
mermaid:
  enable: false
  version: '8.13.5'

# pjax 支持 —— 实验性测试阶段，请谨慎开启
pjax:
  enable: false
  version: '0.2.8'

# main menu navigation
menu:
  Home: ''
#  About: about/
#  Contact: contact/
  Archives: archives/

# stylesheets loaded in the <head>
stylesheets:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/styles/atom-one-dark-reasonable.min.css

# scripts loaded in the end of the body
scripts:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js
```


### _config.yml
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Rhodes Island™
subtitle: blog
description: ''
keywords:
author: Ptilopsis_w
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: arknights

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/misaka-mikoto233/misaka-mikoto233.github.io.git
  branch: main

mathjax:
  tags: none # 或 'ams' 或 'all'
  single_dollars: true # 启用单个美元符号作为内联（行内）数学公式定界符
  cjk_width: 0.9 # 相对 CJK 字符宽度
  normal_width: 0.6 # 相对正常（等宽）宽度
  append_css: true # 将 CSS 添加到每个页面
  every_page: true # 如果为 true，那么无论每篇文章的前题中的 `mathjax` 设置如何，每页都将由 mathjax 呈现

```


### package.json
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "5.4.2"
  },
  "dependencies": {
    "hexo": "^5.0.0",
    "hexo-filter-mathjax": "^0.8.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-searchdb": "^1.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^1.0.0",
    "hexo-renderer-marked": "^4.0.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.1",
    "hexo-renderer-ts": "^1.3.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-wordcount": "^6.0.1"
  }
}

```

**Comment by Yue-plus** [comment]
你是不是下了 [Releases](https://github.com/Yue-plus/hexo-theme-arknights/releases) 页面的压缩包？

不要用那边的压缩包，参考 [#安装](https://github.com/Yue-plus/hexo-theme-arknights#%E5%AE%89%E8%A3%85) 使用 `git clone`

**Comment by misaka-mikoto233** [comment]
我这是在机房电脑搞的，这边系统环境问题很大，git连不上github，请问我手动下载源码可以吗

**Comment by Yue-plus** [comment]
我不保证今后刚刚在码云上同步了仓库，可以使用 <https://gitee.com/yue_plus/hexo-theme-arknights&gt;


（不保证今后会及时更新）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年4月20日(周三) 上午8:33
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [Yue-plus/hexo-theme-arknights] 我的代码块的折叠功能消失了 (Issue #72)




 
我这是在机房电脑搞的，这边系统环境问题很大，git连不上github，请问我手动下载源码可以吗

**Comment by misaka-mikoto233** [comment]
很抱歉再打扰大佬，我最近把机子重装系统了，环境问题搞好了，然后这次我参考安装里的方法用的`git clone`再次装了主题，还是有原来的问题(代码块不能折叠)

下面是`_config.arknights.yml`、`_config.yml`、`package.json`

### _config.arknights.yml
```yml
# html lang
language: zh

# canvas 动态背景
canvas_dust: true

# <body> 背景图片链接
background_image: https://ak.hypergryph.com/assets/index/images/ak/pc/bk.jpg # /img/bg.jpg

# 侧边栏
aside:
  in_left: false # 侧边栏在左 true / false
  logo: https://ak.hypergryph.com/assets/index/images/ak/pc/faction/1.png # 图片链接，建议 1:1 比例
  dr: / # 侧边栏 Dr. 链接
  copyright: # 版权声明、备案号等，可自定义键值，不想显示则留空
    # ©: 1970 to 2020
    # ICP: ——备案号——

# post 文章页面配置；true / false
post:
  date: true # 是否显示发布日期
  updated: true # 是否显示修改日期
  source: true # 是否显示源文件路径
  word_count: true # 是否显示字数统计
  reading_time: false # 是否显示预计阅读时长
  excerpt: true # 是否在文章中显示摘要内容（<!-- more--> 以上的内容）
  reward: false # 文章末显示打赏二维码
# 文章内目录
toc:
  list_number: true # true / false ；是否显示编号
  max_depth: 6 # 最大目录深度
  min_depth: 1 # 最小目录深度
# 归档页；true / false
archives:
  categories_count: true # 是否显示分类总数
  tags_count: true # 是否显示标签总数

# 搜索框
search:
  enable: true

# Valine 无后端评论系统
valine:
  enable: false
  app_id: # APP ID
  app_key: # APP KEY
  server_url: # APP DOMAIN（LeanCloud 国际版）

gitalk:
  enable: false
  client_id: # GitHub Application Client ID
  client_secret: # GitHub Application Client Secret
  repo: # GitHub repository
  owner: # GitHub repository owner
  admin: [] # GitHub repository owner and collaborators (Users who having write access to this repository)
            # Example: [adminA,adminB]
  id: # (optional) The unique id of the page
      # Example: location.pathname

# 图表支持
mermaid:
  enable: false
  version: '8.13.5'

# pjax 支持 —— 实验性测试阶段，请谨慎开启
pjax:
  enable: false
  version: '0.2.8'

# 公式支持
mathjax:
  enable: false
  version: '2.6.1'

# main menu navigation
menu:
  Home: ''
#  About: about/
#  Contact: contact/
  Archives: archives/

# stylesheets loaded in the <head>
stylesheets:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/styles/atom-one-dark-reasonable.min.css

# scripts loaded in the end of the body
scripts:
- //unpkg.com/@highlightjs/cdn-assets@11.4.0/highlight.min.js

```

### _config.yml
```yml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Hexo
subtitle: ''
description: ''
keywords:
author: Ptilopsis_w
language: en
timezone: ''

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: http://example.com
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: true
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: arknights

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# mathjax
mathjax:
  tags: none # 或 'ams' 或 'all'
  single_dollars: true # 启用单个美元符号作为内联（行内）数学公式定界符
  cjk_width: 0.9 # 相对 CJK 字符宽度
  normal_width: 0.6 # 相对正常（等宽）宽度
  append_css: true # 将 CSS 添加到每个页面
  every_page: false # 如果为 true，那么无论每篇文章的前题中的 `mathjax` 设置如何，每页都将由 mathjax 呈现

# wordcount
post:
  count: true # 是否显示字数统计
  time: true # 是否显示阅读时长统计

# search
search:
  enable: true
  preload: true # 非必要
  path: search.json # 非必要，缩小文件用
  format: striptags # 非必要，缩小文件用（该选项能极大缩小搜索数据文件大小，建议开启）
```
### package.json
```json
{
  "name": "hexo-site",
  "version": "0.0.0",
  "private": true,
  "scripts": {
    "build": "hexo generate",
    "clean": "hexo clean",
    "deploy": "hexo deploy",
    "server": "hexo server"
  },
  "hexo": {
    "version": "6.1.0"
  },
  "dependencies": {
    "hexo": "^6.0.0",
    "hexo-browsersync": "^0.3.0",
    "hexo-filter-mathjax": "^0.8.0",
    "hexo-generator-archive": "^1.0.0",
    "hexo-generator-category": "^1.0.0",
    "hexo-generator-index": "^2.0.0",
    "hexo-generator-searchdb": "^1.4.0",
    "hexo-generator-tag": "^1.0.0",
    "hexo-renderer-ejs": "^2.0.0",
    "hexo-renderer-marked": "^5.0.0",
    "hexo-renderer-pug": "^3.0.0",
    "hexo-renderer-stylus": "^2.0.0",
    "hexo-server": "^3.0.0",
    "hexo-theme-landscape": "^0.0.3",
    "hexo-wordcount": "^6.0.1"
  }
}
```
